export enum Routes {
  HOME = '/',
  APP = '/(app)',
  OTP_VERIFY = 'otp-verify',
  SCANNER = '/scanner',
  DASHBOARD = '/dashboard',
  SIGN_IN = '/sign-in',
  APP_DASHBOARD = '/(app)/dashboard',
  APP_DASHBOARD_CORE = '/(app)/dashboard/(core)',
  APP_DASHBOARD_CORE_TEAMS = '/(app)/dashboard/(core)/teams',
  APP_DASHBOARD_CORE_ISSUES = '/(app)/dashboard/(core)/issues',
  APP_DASHBOARD_CORE_NOTIFICATION = '/(app)/dashboard/(core)/notification',
  APP_DASHBOARD_CORE_ISSUES_DETAILS = '/(app)/dashboard/(core)/issues/:id',
  APP_DASHBOARD_TEAM_CREATE = '/(app)/dashboard/team-create',
  APP_ISSUES = '/(app)/issues',
  APP_ISSUES_DETAILS = '/(app)/issues/:id',
  APP_ISSUES_THANKYOU = '/(app)/issues/thankyou',
  APP_ISSUES_CREATE = '/(app)/issues/create',
  DASHBOARD_CORE = '/dashboard/(core)',
  APP_NOTIFICATION = '/(app)/notification',
  DASHBOARD_ISSUES='/dashboard/issues',
}
